language: ruby
rvm:
- '1.9.3'
- '2.0.0'
- 'jruby-19mode'
- 'rbx-19mode'
script:
- "bundle exec rake $RAKE_TEST_TASK"
env:
- "RAKE_TEST_TASK=test"
- "RAKE_TEST_TASK=test:gui"
before_install:
- "sudo apt-get install libX11-dev xorg-dev libgl1-mesa-dev"
- "export CFLAGS=-fPIC $CFLAGS"
- |
  git clone https://github.com/glfw/glfw.git;
  cd glfw; git checkout tags/3.0.2; mkdir build;
  cd build; cmake ..; make; sudo make install;
  cd ../..
install:
- "bundle install"
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
matrix:
  allow_failures:
  - rvm: 'jruby-19mode'
    env: 'RAKE_TEST_TASK=test:gui'
  - rvm: 'rbx-19mode'
    env: 'RAKE_TEST_TASK=test:gui'
