language: ruby
rvm:
- '1.9.3'
- '2.0.0'
script:
- "rake test"
before_install:
- "sudo apt-get install libX11-dev xorg-dev libgl1-mesa-dev"
- "export CFLAGS=-fPIC $CFLAGS"
- |
  git clone https://github.com/glfw/glfw.git;
  cd glfw; git checkout tags/3.0.2; mkdir build;
  cd build; cmake ..; make; sudo make install
- "bundle install"
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
